FROM jusito/docker-ftb-alpine:FTBBase

ENV MY_FILE="Server.jar"

RUN sh /home/entrypoint.sh "https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar" "dc51d617728fdccac2082220aaaf7188" "true"

CMD ["https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar", "dc51d617728fdccac2082220aaaf7188"]