ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-openj9$imageSuffix"

ENV MINECRAFT_VERSION="1.12.2" \
	FORGE_VERSION="14.23.5.2821"

CMD ["https://media.forgecdn.net/files/2690/320/FTB+Presents+Direwolf20+1.12-1.12.2-2.5.0-Server.zip", "fa6263cb3f6d973921d6202e692ce57d"]
