ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-hotspot$imageSuffix"

ENV ROOT_IN_MODPACK_ZIP="" \
	MINECRAFT_VERSION="1.12.2" \
	FORGE_VERSION="14.23.5.2847"

CMD ["https://media.forgecdn.net/files/3074/836/DDSS_Serverfiles_8.0_R1.zip", "33fb9f5258c73d07625d8ac87ec245be"]
