ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-hotspot$imageSuffix"

ENV motd="\u00A7d\u00A7oSky Factory\: 3 Server\u00A7r - \u00A74v3.0.21" \
	\
	MINECRAFT_VERSION="1.10.2" \
	FORGE_VERSION="12.18.3.2511"

CMD ["https://media.forgecdn.net/files/3047/465/FTB_Presents_SkyFactory_3_Server_3_0_21.zip", "e8f12a32a3cdbb9b563862eab5481d4b"]