ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-openj9$imageSuffix"

ENV MINECRAFT_VERSION="1.12.2" \
	FORGE_VERSION="14.23.5.2846"

CMD ["https://media.forgecdn.net/files/2792/352/FTBPresentsStoneblock2Server_1.16.0.zip", "ae25ea85c9cb53328992e035be5fdfec"]
