ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-hotspot$imageSuffix"

ENV allow-flight=true \
    level-type=biomesoplenty \
    motd="Valhelsia 2 Server" \
    \
    MINECRAFT_VERSION="1.15.2" \
	FORGE_VERSION="31.2.50"

CMD ["https://media.forgecdn.net/files/3283/29/Valhelsia_2-2.3.3-SERVER.zip", "c0556560538a3b564c673a6f7ae4b878"]
