ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-hotspot$imageSuffix"

ENV MINECRAFT_VERSION="1.12.2" \
	FORGE_VERSION="14.23.5.2846"

CMD ["https://media.forgecdn.net/files/2778/970/FTBUltimateReloadedServer_1.9.0.zip", "add2832ba8d46b1d5759b92e196d057e"]