#!/bin/sh

#set -o errexit
#set -o pipefail
#set -o nounset 

cd "../modpacks"
for modpack in *
do
	(
	cd "$modpack"
	for version in *
	do
		docker build -t "$DOCKER_REPO:${modpack}-${version}" "$version/."
		docker push "$DOCKER_REPO:${modpack}-${version}"
		#maybe more modpacks/version = to much size used
		docker rmi "$DOCKER_REPO:${modpack}-${version}"
	done
	)
done
