services:
  enigmatica2expertserver-1.83:
    image: jusito/docker-ftb-alpine:8jre-alpine-hotspot
    command: ["https://media.forgecdn.net/files/3433/600/Enigmatica2ExpertServer-1.83.zip", "dcb6ec0691bc0e4385590b9d19e489f2"]
    ports:
      - 25565:25565
    environment:
      MINECRAFT_VERSION: '1.12.2'
      FORGE_VERSION: '14.23.5.2855'
      JAVA_PARAMETERS: '-Xmx5G'
      ADMIN_NAME: ''
      allow_flight: 'true'
      difficulty: '2'
      level_type: 'BIOMESOP'
      max_tick_time: '0'
      motd: 'Enigmatica 2\: Expert Server'
    volumes:
      - enigmatica2expertserver-1.83:/home/docker:rw
    deploy:
      resources:
        limits:
          memory: 7G

volumes:
  enigmatica2expertserver-1.83:
