services:
  mineshaftsnmonsters_normal_serverpack:
    image: jusito/docker-ftb-alpine:8jre-alpine-hotspot
    command: ['https://media.forgecdn.net/files/3455/962/MineshaftsnMonsters++(Normal_Serverpack).zip', '78d1e616daf044b8d6b32a93077be420']
    ports:
      - 25565:25565
    environment:
      MINECRAFT_VERSION: '1.16.5'
      FORGE_VERSION: '36.2.2'
      ADMIN_NAME: ''
      allow_flight: 'true'
      enable_command_block: 'true'
      level_type: 'biomesoplenty'
    volumes:
      - mineshaftsnmonsters_normal_serverpack:/home/docker:rw

volumes:
  mineshaftsnmonsters_normal_serverpack:
