services:
  minecraft_eternal_server_1.4.4:
    image: jusito/docker-ftb-alpine:8jre-alpine-hotspot
    command: ["https://media.forgecdn.net/files/3305/944/Minecraft+Eternal+Server+1.4.4.zip", "38f23c652b14de4ead3a1eef17e2c7a8"]
    ports:
      - 25565:25565
    environment:
      MINECRAFT_VERSION: '1.12.2'
      FORGE_VERSION: '14.23.5.2855'
      JAVA_PARAMETERS: '-Xms2G -Xmx6G -XX:PermSize=256m -Dfml.read.Timeout=560'
      ADMIN_NAME: ''
      enable_command_block: 'true'
      level_type: 'BIOMESOP'
      max_tick_time: '-1'
      motd: 'Minecraft Eternal 1.4.4'
      spawn_protection: '10'
    volumes:
      - minecraft_eternal_server_1.4.4:/home/docker:rw
    deploy:
      resources:
        limits:
          memory: 8G

volumes:
  minecraft_eternal_server_1.4.4:
