services:
  ftb_continuum-1.7.0:
    image: jusito/docker-ftb-alpine:8jre-alpine-hotspot
    command: ["https://api.modpacks.ch/public/modpack/34/149/server/linux", "b5eda1019ba99a06a813aa14b0f0b8ac"]
    ports:
      - 25565:25565
    environment:
      MY_FILE: 'serverinstall_34_149'
      MINECRAFT_VERSION: '1.12.2'
      FORGE_VERSION: '14.23.5.2855'
      JAVA_PARAMETERS: '-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx4096M -Xms3072M'
      ADMIN_NAME: ''
    volumes:
      - ftb_continuum-1.7.0:/home/docker:rw
    deploy:
      resources:
        limits:
          memory: 6144M

volumes:
  ftb_continuum-1.7.0:
