ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-hotspot$imageSuffix"

ENV ROOT_IN_MODPACK_ZIP="Valhelsia_SERVER-2.3.1" \
	MINECRAFT_VERSION="1.15.2" \
	FORGE_VERSION="31.2.47"

CMD ["https://media.forgecdn.net/files/3143/78/Valhelsia_SERVER-2.3.1.zip", "4b89ca932380c70937ef952135b6edcf"]
