FROM jusito/docker-ftb-alpine:8jre-alpine-openj9

ENV MINECRAFT_VERSION="1.12.2" \
	FORGE_VERSION="14.23.5.2796"

CMD ["https://media.forgecdn.net/files/2658/289/FTBContinuumServer_1.6.0.zip", "da48cbbfb86712acee4bd4975aa13cfd"]
