#!/bin/bash

if [ ! -f "test/shared/shared.sh" ]; then exit 1; fi
# shellcheck disable=SC1091
. test/shared/shared.sh
echo "[docker.hook.build][INFO] starting..."

echo "[docker.hook.build][INFO] build base images"
bash test/standard/testBuild.bases.sh

echo "[docker.hook.build][INFO] build modpack images"
bash test/standard/testBuild.modpacks.sh

echo "[docker.hook.build][INFO] successful!"