FROM jusito/docker-ftb-alpine:8jre-alpine-hotspot

ENV MINECRAFT_VERSION="1.10.2" \
	FORGE_VERSION="12.18.3.2477"

CMD ["https://media.forgecdn.net/files/2481/284/FTBPresentsSkyfactory3Server_3.0.15.zip", "a7d54a9937cbf5707efc007caa18a5b6"]