services:
  ftb_revelation-3.5.0:
    image: jusito/docker-ftb-alpine:8jre-alpine-hotspot
    command: ["https://api.modpacks.ch/public/modpack/35/2059/server/linux", "b5eda1019ba99a06a813aa14b0f0b8ac"]
    ports:
      - 25565:25565
    environment:
      MY_FILE: 'serverinstall_35_2059'
      MINECRAFT_VERSION: '1.12.2'
      FORGE_VERSION: '14.23.5.2855'
      JAVA_PARAMETERS: '-XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xmx6144M -Xms4096M'
      ADMIN_NAME: ''
    volumes:
      - ftb_revelation-3.5.0:/home/docker:rw
    deploy:
      resources:
        limits:
          memory: 8192M

volumes:
  ftb_revelation-3.5.0:
