ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-openj9$imageSuffix"

ENV MINECRAFT_VERSION="1.12.2" \
	FORGE_VERSION="14.23.5.2846"

CMD ["https://media.forgecdn.net/files/2778/975/FTBRevelationServer_3.2.0.zip", "9b18c3299e40a0a228d9f99e6bb66630"]