FROM jusito/docker-ftb-alpine:8jre-alpine-hotspot

ENV level_name="Biome Bundle" \
	allow_flight=false \
	level_type="OTG" \
	difficulty=2 \
	max_tick_time=-1 \
	view_distance=8 \
	\
	ROOT_IN_MODPACK_ZIP="RAD-Serverpack-1.39" \
	MINECRAFT_VERSION="1.12.2" \
	FORGE_VERSION="14.23.5.2854"

CMD ["https://media.forgecdn.net/files/3017/949/RAD-Serverpack-1.39.zip", "941d896f6b421230cb157334817c1e4d"]
