ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-hotspot$imageSuffix"

ENV ROOT_IN_MODPACK_ZIP="" \
	MINECRAFT_VERSION="1.12.2" \
	FORGE_VERSION="14.23.5.2847"

CMD ["https://media.forgecdn.net/files/2959/20/DDSS_Serverfiles_V.7.4a.zip", "19b4ddcdd9b699af8645afd657283d7c"]
