ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-openj9$imageSuffix"

ENV MINECRAFT_VERSION="1.7.10" \
	FORGE_VERSION="10.13.4.1614"

CMD ["https://media.forgecdn.net/files/2731/545/FTBInfinityServer_3.1.0.zip", "5fd22d9c01ab783a3bee177a5c4d5f22"]
