ARG imageSuffix=""

FROM "jusito/docker-ftb-alpine:8jre-alpine-hotspot$imageSuffix"

ENV ROOT_IN_MODPACK_ZIP="Valhelsia_SERVER-3.1.1" \
	MINECRAFT_VERSION="1.16.4" \
	FORGE_VERSION="35.1.13"

CMD ["https://media.forgecdn.net/files/3145/66/Valhelsia_SERVER-3.1.1.zip", "5ed2dde2e751118010a1c3e3895168f2"]
